apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
  
spec: 
  replicas: 1
#POD template
  template:
    metadata:
      labels:
        app: go-web-app

#Image from which pods are created
    spec:
      containers:
      - name: go-web-app
        image: faizan0007/go-web-app:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080

          